@startuml

class HeroAircraft {
    - {static} instance: HeroAircraft
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + {static} getInstance(): HeroAircraft
    + forward(): void
    + shoot(): List<BaseBullet>
}

HeroAircraft::instance -[hidden]-> HeroAircraft
HeroAircraft::instance -left-> HeroAircraft

@enduml

